# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KMmPHI79bYNbONN67SFQp-tIq9HVCNrW
"""

import random

def rock_paper_scissors():
    print("✊ 🖐 ✌️ Welcome to Rock, Paper, Scissors!")
    options = ["rock", "paper", "scissors"]

    while True:
        user_choice = input("Choose rock, paper, or scissors (or type 'exit' to quit): ").lower()

        if user_choice == "exit":
            print("👋 Thanks for playing!")
            break

        if user_choice not in options:
            print("❌ Invalid choice. Try again.")
            continue

        computer_choice = random.choice(options)
        print(f"Computer chose: {computer_choice}")

        if user_choice == computer_choice:
            print("😐 It's a tie!")
        elif (
            (user_choice == "rock" and computer_choice == "scissors") or
            (user_choice == "scissors" and computer_choice == "paper") or
            (user_choice == "paper" and computer_choice == "rock")
        ):
            print("✅ You win!")
        else:
            print("❌ You lose!")

# Run the game
rock_paper_scissors()